// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: module/record/interfaces/http/grpc/pb/record.proto

package record

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecordRequest) Reset() {
	*x = CreateRecordRequest{}
	mi := &file_module_record_interfaces_http_grpc_pb_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecordRequest) ProtoMessage() {}

func (x *CreateRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_record_interfaces_http_grpc_pb_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateRecordRequest) Descriptor() ([]byte, []int) {
	return file_module_record_interfaces_http_grpc_pb_record_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRecordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateRecordRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type GetRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecordRequest) Reset() {
	*x = GetRecordRequest{}
	mi := &file_module_record_interfaces_http_grpc_pb_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecordRequest) ProtoMessage() {}

func (x *GetRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_module_record_interfaces_http_grpc_pb_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecordRequest.ProtoReflect.Descriptor instead.
func (*GetRecordRequest) Descriptor() ([]byte, []int) {
	return file_module_record_interfaces_http_grpc_pb_record_proto_rawDescGZIP(), []int{1}
}

func (x *GetRecordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordResponse) Reset() {
	*x = RecordResponse{}
	mi := &file_module_record_interfaces_http_grpc_pb_record_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordResponse) ProtoMessage() {}

func (x *RecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_module_record_interfaces_http_grpc_pb_record_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordResponse.ProtoReflect.Descriptor instead.
func (*RecordResponse) Descriptor() ([]byte, []int) {
	return file_module_record_interfaces_http_grpc_pb_record_proto_rawDescGZIP(), []int{2}
}

func (x *RecordResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecordResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *RecordResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_module_record_interfaces_http_grpc_pb_record_proto protoreflect.FileDescriptor

const file_module_record_interfaces_http_grpc_pb_record_proto_rawDesc = "" +
	"\n" +
	"2module/record/interfaces/http/grpc/pb/record.proto\x12\x06record\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n" +
	"\x13CreateRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"\"\n" +
	"\x10GetRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"n\n" +
	"\x0eRecordResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\x128\n" +
	"\tcreatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2]\n" +
	"\x14RecordCommandService\x12E\n" +
	"\fCreateRecord\x12\x1b.record.CreateRecordRequest\x1a\x16.record.RecordResponse\"\x002Y\n" +
	"\x12RecordQueryService\x12C\n" +
	"\rGetRecordByID\x12\x18.record.GetRecordRequest\x1a\x16.record.RecordResponse\"\x00B.Z,module/record/interfaces/http/grpc/pb;recordb\x06proto3"

var (
	file_module_record_interfaces_http_grpc_pb_record_proto_rawDescOnce sync.Once
	file_module_record_interfaces_http_grpc_pb_record_proto_rawDescData []byte
)

func file_module_record_interfaces_http_grpc_pb_record_proto_rawDescGZIP() []byte {
	file_module_record_interfaces_http_grpc_pb_record_proto_rawDescOnce.Do(func() {
		file_module_record_interfaces_http_grpc_pb_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_module_record_interfaces_http_grpc_pb_record_proto_rawDesc), len(file_module_record_interfaces_http_grpc_pb_record_proto_rawDesc)))
	})
	return file_module_record_interfaces_http_grpc_pb_record_proto_rawDescData
}

var file_module_record_interfaces_http_grpc_pb_record_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_module_record_interfaces_http_grpc_pb_record_proto_goTypes = []any{
	(*CreateRecordRequest)(nil),   // 0: record.CreateRecordRequest
	(*GetRecordRequest)(nil),      // 1: record.GetRecordRequest
	(*RecordResponse)(nil),        // 2: record.RecordResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_module_record_interfaces_http_grpc_pb_record_proto_depIdxs = []int32{
	3, // 0: record.RecordResponse.createdAt:type_name -> google.protobuf.Timestamp
	0, // 1: record.RecordCommandService.CreateRecord:input_type -> record.CreateRecordRequest
	1, // 2: record.RecordQueryService.GetRecordByID:input_type -> record.GetRecordRequest
	2, // 3: record.RecordCommandService.CreateRecord:output_type -> record.RecordResponse
	2, // 4: record.RecordQueryService.GetRecordByID:output_type -> record.RecordResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_module_record_interfaces_http_grpc_pb_record_proto_init() }
func file_module_record_interfaces_http_grpc_pb_record_proto_init() {
	if File_module_record_interfaces_http_grpc_pb_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_module_record_interfaces_http_grpc_pb_record_proto_rawDesc), len(file_module_record_interfaces_http_grpc_pb_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_module_record_interfaces_http_grpc_pb_record_proto_goTypes,
		DependencyIndexes: file_module_record_interfaces_http_grpc_pb_record_proto_depIdxs,
		MessageInfos:      file_module_record_interfaces_http_grpc_pb_record_proto_msgTypes,
	}.Build()
	File_module_record_interfaces_http_grpc_pb_record_proto = out.File
	file_module_record_interfaces_http_grpc_pb_record_proto_goTypes = nil
	file_module_record_interfaces_http_grpc_pb_record_proto_depIdxs = nil
}
